name: Linkbase

services:
  frontend:
    container_name: linkbase-frontend-1
    restart: always
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - backend
    environment:
      - API_URL=http://linkbase-backend-1
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - app-network
    volumes:
      - ${PWD}/frontend/src:/app/src
  backend:
    container_name: linkbase-backend-1
    restart: always
    ports:
      - 80:80
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:admin12345@linkbase-database-1:5432/link
    networks:
      - app-network
    volumes:
      - ${PWD}/backend:/app

  database:
    container_name: linkbase-database-1
    image: postgres:latest
    shm_size: 128mb
    restart: always
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - app-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=link
  adminer:
    container_name: linkbase-adminer-1
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:

volumes:
  app-storage:
