name: linkbase pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run containers on remote
        uses: appleboy/ssh-action@master
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~ || exit
            if [ ! -d "linkbase" ]; then
            git clone https://github.com/SucksToBeAnik/linkbase.git
            fi
            cd linkbase || exit
            git pull origin main
            docker compose up -d --build
